# Generated by Django 3.2 on 2020-08-31 15:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=20, verbose_name='Address')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('food_type', models.CharField(choices=[('D', 'Dietary'), ('VF', 'Vegetable and Fruits'), ('K', 'Korean Food'), ('C', 'Chinese Food'), ('T', 'Taiwan Food')], max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='food_pictures')),
                ('price', models.IntegerField()),
                ('quality', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('N', 'Normal'), ('B', 'Bad'), ('VB', 'Very Bad')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=20, verbose_name='Address')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='staff_pictures/default.jpg', upload_to='staff_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ordered By')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateField(auto_now_add=True)),
                ('purchased_time', models.TimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ordered By')),
                ('food_to_order', models.ManyToManyField(to='staff.OrderFood')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='food_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.supplier'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=True)),
                ('deliver_request_date', models.DateField(auto_now_add=True)),
                ('deliver_request_time', models.TimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.customer')),
                ('food_to_deliver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.foodcart')),
                ('staff_to_deliver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=1)),
                ('payment_method', models.CharField(choices=[('M', 'Master'), ('F', 'Visa'), ('F', 'Paypal'), ('F', 'Cash'), ('F', 'Transfer')], max_length=20)),
                ('name_on_card', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food_cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.foodcart')),
            ],
        ),
    ]
