# Generated by Django 3.2 on 2020-08-31 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_delivery_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='food_to_deliver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.foodcart'),
        ),
    ]
